### ISSUE TITLE
Inappropriate Conduct

### ISSUE THREAD

**Issue by amark** [holepunchto/.github#3]
A member of your community "@stevenfranssen:matrix.org" has relentlessly been advertising/recruiting for you in my (and I'm sure, other) communities. I told him last month that he must have a $99/mo sponsorship towards our Open Source project to advertise recruiting links, he never paid, and then started doing it again in the name of Keet/Pears/Holepunch.

I'd like to send him a bill, but can't find his contact. The total owned is $99 * 2mo = $198, will you direct me to him or be willing to pick up the tab https://github.com/sponsors/amark ? Thanks.

**Comment by mafintosh** [comment]
Sorry, dont know anything about this
